# Arch rules ({{PROJECT_NAME}})
# Generated by init-project.js
name: Arch rules

on:
  pull_request:
  push:
    branches: [main]

jobs:
  arch:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run arch rules
        run: npm run audit:arch
