# Dependency Cruiser ({{PROJECT_NAME}})
# Generated by init-project.js
name: Dependency Cruiser

on:
  pull_request:
  push:
    branches: [main]

jobs:
  dep-cruiser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run dependency-cruiser
        run: npx dependency-cruiser --config dependency-cruiser.config.mjs .
