# Knip 未使用 export / dependency 検出 ({{PROJECT_NAME}})
# Generated by init-project.js
name: Knip

on:
  pull_request:
  push:
    branches: [main]

jobs:
  knip:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Knip (warn-only mode)
        run: npx knip --no-exit-code
