# Property tests ({{PROJECT_NAME}})
# Generated by init-project.js
name: Property tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  property:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run property tests
        run: npx vitest run tests/property
