# Semgrep custom rules ({{PROJECT_NAME}})
# Generated by init-project.js
name: Semgrep

on:
  pull_request:
  push:
    branches: [main]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Semgrep
        run: pip install semgrep
      - name: Run Semgrep custom rules
        run: semgrep --config scripts/zeroact-test-commons/semgrep-rules/{{PROJECT_NAME}}/ --error --metrics off
