'use strict';
// ============================================================
// ★★使っていない 道路グラフを repo に 戻さない★★ 2026-08-30
//
//   ★どちらの物差しか★
//     ★距離でも 料金でも ありません★。★お金（Vercel の 請求）★を 見ます。
//     ★客の 課金距離には 1mも 触りません★（消した物を 客は 1本も 取りに行きません）。
//
//   ★何を 消したか（2026-08-30・司さん「課金距離変わらんならやれや」）★
//     data/road-graph-<県>.js …………… 47本 1,023 MB
//     data/road-graph-tiles/<県>/…… 15,896本 約1,090 MB
//     ＝合計 ★約2.1GB★（repo 3.22GB の 65%）
//
//   ★なぜ 消してよいと 判断したか（全部 数えた）★
//     ・客側（index.html / sw.js / js/*.js）に `road-graph-tiles` … ★0箇所★
//     ・客側で `road-graph-<県>.js` を 呼ぶ 所 …………………………… ★0箇所★
//       （使うのは road-graph-backbone-jp.js だけ。★これは 残しています★）
//     ・試験で 使う 所 ……………………………………………………………… ★0本★
//     ・画面の 注記「★旧 region-loader.js / road-graph-tile-loader.js（2026-05-13 大改修 C11）★」
//       ＝★読む 仕組みは その時に 外れ、データだけ 残っていました★
//
//   ★作り直せます★
//     どちらも 頭に「Auto-generated by scripts/build-road-graph(-tiled).js」と 書いてあり、
//     元(data/roads-<県>.js)も 作る道具(scripts/)も ★repo に 残っています★。
//     さらに ★git の 履歴に そのまま 残ります★（いつでも 取り出せます）。
//
//   ★ここで 見る事★
//     ①消した物を ★客側が 呼び始めていない★（呼ぶなら データが 無いので 壊れます）
//     ②★作り直す道具★が 残っている
//     ③★元のデータ★(roads-<県>.js)が 残っている
//     ④★使っている backbone★ は 消していない
//     ⑤★消した物が repo に 戻ってきていない★（また 3.2GB に しない）
// ============================================================
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const DATA = path.join(ROOT, 'data');

function kokyakuSrc() {
  let s = '';
  for (const p of ['index.html', 'sw.js']) {
    const fp = path.join(ROOT, p);
    if (fs.existsSync(fp)) s += fs.readFileSync(fp, 'utf8') + '\n';
  }
  const jsDir = path.join(ROOT, 'js');
  for (const f of fs.readdirSync(jsDir)) {
    if (f.endsWith('.js')) s += fs.readFileSync(path.join(jsDir, f), 'utf8') + '\n';
  }
  // ★注記は 外す★（説明の 中の 名前で 赤に しない）
  return s.replace(/^\s*(\/\/|\*|<!--).*$/gm, '');
}

describe('★使っていない 道路グラフを repo に 戻さない（Vercel の お金）★', () => {
  const src = kokyakuSrc();

  it('★① 客側が road-graph-tiles を 呼んでいない★', () => {
    expect(
      src.includes('road-graph-tiles'),
      '★消したデータを 呼んでいます（データが 無いので 壊れます）★'
    ).toBe(false);
  });

  it('★② 客側が road-graph-<県>.js を 呼んでいない（backbone は 別）★', () => {
    // ★2026-08-30 直し★: はじめ `road-graph-[a-z]+` で 探して
    //   ★作る道具の 名前（build-road-graph-tiled.js）まで 拾って 赤に なりました★。
    //   ⇒★data/ の 物だけ★を 見ます（呼んでいるか、を 見たいので）。
    const hits = (src.match(/\/data\/road-graph-[a-z-]+/g) || []).filter(
      (x) => !x.startsWith('/data/road-graph-backbone')
    );
    expect(hits, '★県ごとの 道路グラフを 呼んでいます★').toEqual([]);
  });

  it('★③ 作り直す 道具が 残っている★', () => {
    ['build-road-graph.js', 'build-road-graph-tiled.js'].forEach((f) => {
      expect(fs.existsSync(path.join(ROOT, 'scripts', f)), '★作り直せません: ' + f + '★').toBe(
        true
      );
    });
  });

  it('★④ 元のデータ(roads-<県>.js)が 残っている★', () => {
    const roads = fs.readdirSync(DATA).filter((f) => /^roads-[a-z]+\.js$/.test(f));
    expect(roads.length, '★元のデータが 足りません（作り直せません）★').toBeGreaterThanOrEqual(47);
  });

  it('★⑤ 使っている backbone は 消していない★', () => {
    expect(
      fs.existsSync(path.join(DATA, 'road-graph-backbone-jp.js')),
      '★使っている 道路グラフを 消しました★'
    ).toBe(true);
    expect(src, '★backbone を 呼ぶ 所が 消えました★').toContain('road-graph-backbone-jp.js');
  });

  it('★★⑥ 消した物が repo に 戻ってきていない★★', () => {
    expect(
      fs.existsSync(path.join(DATA, 'road-graph-tiles')),
      '★タイルが 戻っています（また 3.2GB に なります）★'
    ).toBe(false);
    const kenGoto = fs
      .readdirSync(DATA)
      .filter((f) => /^road-graph-[a-z]+\.js$/.test(f) && f !== 'road-graph-backbone-jp.js');
    expect(kenGoto, '★県ごとの 道路グラフが 戻っています★').toEqual([]);
  });
});
